#%RAML 1.0 DataType

type: object
properties:
  FFDCUSN : 
    type: string
    maxLength: 10
  FFDCNMB ?: 
    type: string
    maxLength: 25
  FFDCA1B ?: 
    type: string
    maxLength: 25
  FFDCA2B ?: 
    type: string
    maxLength: 25
  FFDCTYB ?: 
    type: string
    maxLength: 15
  FFDSTEB ?: 
    type: string
    maxLength: 3 
  FFDZPCB ?: 
    type: string
    maxLength: 10
  FFDSCEM ?: 
    type: string
    maxLength: 50
  FFDSCAC ?: 
    type: string
    maxLength: 25
  FFDSAEM ?: 
    type: string
    maxLength: 50
  FFDSCPA ?: 
    type: string
    maxLength: 25
  FFDSPEM ?: 
    type: string
    maxLength: 50
  FFDPHNB ?: 
    type: string
    maxLength: 10
  FFDSLNB ?: 
    type: string
    maxLength: 3
  FFDCSCD ?: 
    type: string
    maxLength: 5
  FFDTRMC ?: 
    type: string
    maxLength: 3
  FFDINSI ?: 
    type: string
    maxLength: 25
  FFDDTEI ?: 
    type: string
    maxLength: 8
  FFDDTEL ?: 
    type: string
    maxLength: 8
  FFDDTBC ?: 
    type: string
    maxLength: 8
  FFDDSOA ?: 
    type: number
    format: int
    maximum: 999
  FFDAMDU ?:  
    type: number
    multipleOf: 0.01
  FFDAGE0 ?: 
    type: number
    multipleOf: 0.01
  FFDAGE1 ?: 
    type: number
    multipleOf: 0.01
  FFDAGE2 ?: 
    type: number
    multipleOf: 0.01
  FFDAGE3 ?:
    type: number
    multipleOf: 0.01
  FFDAGE4 ?:
    type: number
    multipleOf: 0.01
  FFDPHNF ?:
    type: string
    maxLength: 10
  FFDORGN ?:
    type: string
    maxLength: 10
  FFDLSPY ?:
    type: number
    multipleOf: 0.01
  FFDCGRP ?:
    type: string
    maxLength: 5
