#%RAML 1.0 DataType

type: object
properties:
  FFCCMPN ?: 
    type: string
    maxLength : 3
  FFCCUSN : 
    type: string
    maxLength : 10
  FFCARCD ?: 
    type: string
    maxLength : 1
  FFCCNMB ?: 
    type: string
    maxLength : 25
  FFCCA1B ?: 
    type: string
    maxLength : 25
  FFCCA2B ?: 
    type: string
    maxLength : 25
  FFCCTYB ?: 
    type: string
    maxLength : 15
  FFCSTEB ?: 
    type: string
    maxLength : 2
  FFCZPCB ?: 
    type: string
    maxLength : 10
  FFCBCEM ?: 
    type: string
    maxLength : 50
  FFCBCWS ?: 
    type: string
    maxLength : 50
  FFCBCAC ?: 
    type: string
    maxLength : 25
  FFCBAEM ?: 
    type: string
    maxLength : 50
  FFCBCPA ?: 
    type: string
    maxLength : 25
  FFCBPEM ?: 
    type: string
    maxLength : 50
  FFCPHNB ?: 
    type: string
    maxLength : 10
  FFCCDTE ?: 
    type: string
    maxLength : 8
  FFCPHNF ?: 
    type: string
    maxLength : 10
  