#%RAML 1.0 DataType
type: object
properties:
  FFIITMN :
    type: string
    maxLength: 10
  FFIARCD ?:
    type: string
    maxLength: 1
  FFIPCKI ?:
    type: string
    maxLength: 4
  FFISZEI ?:
    type: string
    maxLength: 7
  FFIUPCN ?:
    type: string
    maxLength: 25
  FFIIDE1 ?:
    type: string
    maxLength: 40
  FFIIDE2 ?:
    type: string
    maxLength: 40
  FFIWTIW ?:
    type: number
    multipleOf: 0.001
  FFIWTET ?:
    type: number
    multipleOf: 0.001
  FFICWCD ?:
    type: string
    maxLength: 1
  FFICBEC ?:
    type: number
  FFIBRDN ?:
    type: string
    maxLength: 15
  FFIHGTH ?:
    type: number
    multipleOf: 0.001
  FFIWDTH ?:
    type: number
    multipleOf: 0.001
  FFIDPTH ?:
    type: number
    multipleOf: 0.001
  FFIBNCD ?:
    type: string
    maxLength: 5
