#%RAML 1.0 DataType
type: object
properties:
  HHHCMPN ?:
    type: string
    maxLength: 3
  HHHDIVN ?:
    type: string
    maxLength: 3
  HHHDPTN ?:
    type: string
    maxLength: 3
  HHHCUSN ?:
    type: string
    maxLength: 10
  HHHORNR :
    type: string
    maxLength: 7
  HHHORTY ?:
    type: string
    maxLength: 1
  HHHMEMO ?:
    type: string
    maxLength: 3
  HHHMEM2 ?:
    type: string
    maxLength: 3
  HHHWHSN ?:
    type: string
    maxLength: 3
  HHHSETN ?:
    type: string
    maxLength: 5
  HHHCNMB ?:
    type: string
    maxLength: 25
  HHHCA1B ?:
    type: string
    maxLength: 25
  HHHCA2B ?:
    type: string
    maxLength: 25
  HHHCTYB ?:
    type: string
    maxLength: 15
  HHHSTEB ?:
    type: string
    maxLength: 3
  HHHZPCB ?:
    type: string
    maxLength: 10
  HHHARCD ?:
    type: string
    maxLength: 1
  HHHSLNB ?:
    type: string
    maxLength: 3
  HHHDTES ?:
    type: string
    maxLength: 8
  HHHDTET ?:
    type: string
    maxLength: 8
  HHHINSI ?:
    type: string
    maxLength: 25
  HHHINS2 ?:
    type: string
    maxLength: 25
  HHHINVR ?:
    type: string
    maxLength: 7
  HHHTRMC ?:
    type: string
    maxLength: 3
  HHHUSER :
    type: string
    maxLength: 10
  HHHUSR1 ?:
    type: string
    maxLength: 10
  HHHUSR2 ?:
    type: string
    maxLength: 10
  HHHTIMO ?:
    type: string
    maxLength: 6
  HHHTIME ?:
    type: string
    maxLength: 6
  HHHFSYR ?:
    type: string
    maxLength: 4
  HHHFSPD ?:
    type: string
    maxLength: 2
  HHHWEKC ?:
    type: string
    maxLength: 2
  HHHCLYR ?:
    type: string
    maxLength: 4
  HHHCLWK ?:
    type: string
    maxLength: 2
  HHHINVN ?:
    type: string
    maxLength: 7
  HHHDTEI ?:
    type: string
    maxLength: 8
  HHHINAM ?:
    type: number
    multipleOf: 0.01
  HHHQYOA ?:
    type: number
    format: int
  HHHQYSA ?:
    type: number
    format: int
  HHHEXCB ?:
    type: number
  HHHEXSH ?:
    type: number
    multipleOf: 0.001
  HHHEXSG ?:
    type: number
    multipleOf: 0.01
  HHHEXSN ?:
    type: number
    multipleOf: 0.01
  HHHEXCG ?:
    type: number
    multipleOf: 0.01
  HHHEXCR ?:
    type: number
    multipleOf: 0.01
  HHHEXAC ?:
    type: number
    multipleOf: 0.01
  HHHEXBS ?:
    type: number
    multipleOf: 0.01
  HHHEXMC ?:
    type: number
    multipleOf: 0.01
  HHHEXRC ?:
    type: number
    multipleOf: 0.01
  HHHCSCD ?:
    type: string
    maxLength: 5