#%RAML 1.0 DataType
type: object
properties:
  HHICUSN ?:
    type: string 
    maxLength: 10
  HHIORNR :
    type: string 
    maxLength: 7
  HHILNOI :
    type: string 
    maxLength: 5
  HHIMEMO ?:
    type: string 
    maxLength: 3
  HHICRIN ?:
    type: string 
    maxLength: 1
  HHIDTES ?:
    type: string 
    maxLength: 8
  HHIDTET ?:
    type: string 
    maxLength: 8
  HHIRTEN ?:
    type: string 
    maxLength: 5
  HHIITMN ?:
    type: string 
    maxLength: 10
  HHIQYOA ?:
    type: number 
    format : int
  HHIQYSA ?:
    type: number 
    format : int
  HHIPRCN ?:
    type: number 
  HHIPRCG ?:
    type: number 
  HHICSTS ?:
    type: number 
  HHICSTY ?:
    type: number 
  HHICSTZ ?:
    type: number 
  HHICSTM ?:
    type: number 
  HHICSTR ?:
    type: number
  HHIPBHN ?:
    type: string 
    maxLength: 5
  HHIPBHF ?:
    type: string 
    maxLength: 7
  HHIWHNA ?:
    type: string 
    maxLength: 3
  HHIVNDN ?:
    type: string 
    maxLength: 10
  HHICLSN ?:
    type: string 
    maxLength: 3
  HHICRDC ?:
    type: string 
    maxLength: 3
  HHIEXSG ?:
    type : number
    multipleOf : 0.01
  HHIEXSN ?:
    type : number
    multipleOf : 0.01
  HHIEXCG ?:
    type : number
    multipleOf : 0.01
  HHIEXCR ?:
    type : number
    multipleOf : 0.01
  HHIEXAC ?:
    type : number
    multipleOf : 0.01