api:
  name: ${project.name}
  version: ${project.version}
  env: ${mule.env}

json:
  logger:
    application:
      name: ${project.name}
      version: ${project.version}
    
sfdc:
  customerMaster:
    object: "Account"
    externalId: "Customer_Number__c"
  customerShipTo:
    object: "Account"
    externalId: "Customer_Number__c"
  product:
    object: "Product2"
    externalId: "Product_Code_External__c"
  salesOrder:
    object: "Sales_Order__c"
    externalId: "Order_Number__c"  
  salesOrderDetails:
    object: "Sales_Order_Line__c"
    externalId: "Order_Number_Line_External__c"  
    
sftp:
  directory:
      customermaster:
        input: "In/Customer Master"
        failed: "Errors/Customer Master"
        output: "Out/Customer Master"
      customershipto:
        input: "In/Customer Ship To"
        failed: "Errors/Customer Ship To"
        output: "Out/Customer Ship To"
      itemMaster:
        input: "In/Item Master"
        failed: "Errors/Item Master"
        output: "Out/Item Master"
      salesOrderHeader:
        input: "In/Sales Order Header"
        failed: "Errors/Sales Order Header"
        output: "Out/Sales Order Header"
      salesOrderLineItems:
        input: "In/Sales Order Line Items"
        failed: "Errors/Sales Order Line Items"
        output: "Out/Sales Order Line Items"
  schedulerExpresssion:
      customermaster: "0 0 8,12,16,20 ? * *"
      customershipto: "0 10 8,12,16,20 ? * *"
      itemMaster: "0 20 8,12,16,20 ? * *"
      salesOrderHeader: "0 30 8,12,16,20 ? * *"
      salesOrderLineItems: "0 40 8,12,16,20 ? * *"

flowState:
  customerMaster: "stopped"
  customerShipTo: "stopped"
  product: "stopped"
  salesOrderHeader: "stopped"
  salesOrderLineItems: "stopped"
  
log:
  category:
    conversion: "log.conversion"
    contract: "log.contract"
    orders: "log.order"
    sftp: "log.sftp"
    sfdc: "log.sfdc"
    product: "log.product"