#%RAML 1.0 NamedExample
value:
  - FFDCUSN: PAM1815
    FFDCNMB: HIP HOP FISH & CHICKEN
    FFDCA1B: 3263 DONNELL DR
    FFDCA2B: 
    FFDCTYB: DISTRICT HEIGHT
    FFDSTEB: MD
    FFDZPCB: "20747"
    FFDSCEM: LITHE.MAGATHEH@YAHOO.COM
    FFDSCAC: LITHE MAGATHEH
    FFDSAEM: LITHE.MAGATHEH@YAHOO.COM
    FFDSCPA: 347.476.4590
    FFDSPEM: KRAZY1/KRAZY2/KRAZY3/HAR108/BELLA94/CRO229/MAYA94
    FFDPHNB: "8563086695"
    FFDSLNB: "94"
    FFDCSCD: HIP
    FFDTRMC: "1"
    FFDINSI:
    FFDDTEI: "20250715"
    FFDDTEL: "20250716"
    FFDDTBC: "20250715"
    FFDDSOA: 0
    FFDAMDU: 0.00
    FFDAGE0: 0.00
    FFDAGE1: 0.00
    FFDAGE2: 0.00
    FFDAGE3: 0.00
    FFDAGE4: 0.00
    FFDPHNF: 0.00
    FFDORGN: URO024
    FFDLSPY: 5676.77
    FFDCGRP: URO