#%RAML 1.0 NamedExample
value:
  - FFCCMPN: "1"
    FFCCUSN: MAYA294
    FFCARCD: A
    FFCCNMB: FIRST AVE RESTAURANT LLC
    FFCCA1B: 1586 1ST AVE
    FFCCA2B: 1586 1ST AVE
    FFCCTYB: NEW YORK
    FFCSTEB: NJ
    FFCZPCB: "10028"
    FFCBCEM: MAXI66588@GMAIL.COM
    FFCBCWS: www.mytestwebsite.com
    FFCBCAC: SUKHINDER SINGH
    FFCBAEM: MAXI66588@GMAIL.COM
    FFCBCPA: 347.476.4590
    FFCBPEM: KRAZY1/KRAZY2/HAR108/BELLA94/CRO229/MAYA94/MAYA394
    FFCPHNB: "3474764590"
    FFCCDTE: "20250714"
    FFCPHNF: "0"
