#%RAML 1.0 NamedExample
value:
  - FFIITMN: "083030"
    FFIARCD: A
    FFIPCKI: "1"
    FFISZEI: 3000 CT
    FFIUPCN: "80850031618738"
    FFIIDE1: BROADWAY-GP PAPER 12X12
    FFIIDE2: 
    FFIWTIW: 24.37
    FFIWTET: 0
    FFICWCD: N
    FFICBEC: 0.690252
    FFIBRDN: 
    FFIHGTH: 12.8
    FFIWDTH: 12.8
    FFIDPTH: 7.28
    FFIBNCD: PACR