#%RAML 1.0 NamedExample
{
  "isSuccess": true,
  "apiName": "mfq-api-integration",
  "apiVersion": "1.0.0",
  "traceId": "19700bda-ea6c-4f39-ad7d-3c62a5e25968",
  "timestamp": "2025-01-01T00:00:00Z",
  "message": "Success",
  "sfResponse": "[{\"id\":\"0035g00002KkXsGAAV\",\"success\":true,\"errors\":[]}]"

}