#%RAML 1.0 NamedExample
value:
- HHICUSN : PAM1714
  HHIORNR : "2956016"
  HHILNOI : "1"
  HHIMEMO : CTC
  HHICRIN : Y
  HHIDTES : "20250723"
  HHIDTET : "20250723"
  HHIRTEN : WED
  HHIITMN : "9999999999"
  HHIQYOA : 4
  HHIQYSA : 4
  HHIPRCN : 72.386
  HHIPRCG : 72.386
  HHICSTS : 63.28
  HHICSTY : 63.28
  HHICSTZ : 63.28
  HHICSTM : 63.28
  HHICSTR : 70.3111
  HHIPBHN : "2021"
  HHIPBHF : "2021005"
  HHIWHNA : DRY
  HHIVNDN : GIR100
  HHICLSN : CTC
  HHICRDC : CTC
  HHIEXSG : 289.54
  HHIEXSN : 289.54
  HHIEXCG : 253.12
  HHIEXCR : 253.12
  HHIEXAC : 253.12