#%RAML 1.0 NamedExample
value:
- HHHCMPN : "1"
  HHHDIVN : "1"
  HHHDPTN : "1"
  HHHCUSN : PAM1714
  HHHORNR : "2956016"
  HHHORTY : I
  HHHMEMO : CTC
  HHHMEM2 : 
  HHHWHSN : "1"
  HHHSETN : "0"
  HHHCNMB : AKS HALAL BITES 739
  HHHCA1B : 739 FERRY CUT OFF ST
  HHHCA2B : 
  HHHCTYB : NEW CASTLE
  HHHSTEB : DE
  HHHZPCB : "19720"
  HHHARCD : A
  HHHSLNB : "278"
  HHHDTES : "20250723"
  HHHDTET : "20250723"
  HHHINSI : CTC ADJ UNCOLL. DB BAL
  HHHINS2 : INV 2314548
  HHHINVR : "2345686"
  HHHTRMC : "1"
  HHHUSER : MAGGIEY
  HHHUSR1 : MAGGIEY
  HHHUSR2 : MAGGIEY
  HHHTIMO : "121451"
  HHHTIME : "121439"
  HHHFSYR : "2025"
  HHHFSPD : "7"
  HHHWEKC : "30"
  HHHCLYR : "2025"
  HHHCLWK : "30"
  HHHINVN : "2345686"
  HHHDTEI : "20250723"
  HHHINAM : 1407.02
  HHHQYOA : 27
  HHHQYSA : 27
  HHHEXCB : 27.252223
  HHHEXSH : 1059.95
  HHHEXSG : 1407.02
  HHHEXSN : 1407.02
  HHHEXCG : 1335.35
  HHHEXCR : 1335.35
  HHHEXAC : 1335.04
  HHHEXBS : 665.12
  HHHEXMC : 1335.04
  HHHEXRC : 1395.88
  HHHCSCD : "99"