#%RAML 1.0 NamedExample

apiName: "mqf-api-integration"
apiVersion: "1.0.0"
traceId: "19700bda-ea6c-4f39-ad7d-3c62a5e25968"
timestamp: "2025-01-01T00:00:00Z"
errorDetails:
  -
    errorType: "HTTP:UNAUTHORIZED"
    errorMessage: "Authentication failed"
    errorSource: "Mulesoft"